ChibiOS/ChibiOS-Contrib

- os/hal/ports/NRF51/NRF51822/pal_lld.c
The DIR bit in the PIN_CNF will override the DIR/DIRSET/DIRCLR register changes, so I think they redundant and not needed here.
> nRF51: Remove unnecessary direction setting

- demos/NRF51/RT-WVSHARE_BLE400/main.c
- os/hal/ports/NRF51/NRF51822/serial_lld.c
- os/hal/ports/NRF51/NRF51822/serial_lld.h
Use values from bitfields header. Also convert notify1 function to be
non-blocking, which seems to be how most of the other serial drivers are
implemented.
> Cleanup nRF51 serial driver

- os/common/ports/ARMCMx/compilers/GCC/ld/NRF51822.ld
linker was generating a warning, and tests were failing on "Heap, allocation and fragmentation test"
> Added missing HEAP_RAM definition

- os/hal/boards/NRF51-DK/board.mk
- os/various/gdb.mk
- os/various/jlink.mk
Adding two make file (jlink.mk and gdb.mk), to simplify development by adding to the Makefile
```
include $(CHIBIOS_CONTRIB)/os/various/jlink.mk
include $(CHIBIOS_CONTRIB)/os/various/gdb.mk
flash: all jlink-flash
debug: gdb-debug
```
> Ease dev with flash/debug target helper

- demos/MSP430X/NIL-EXP430FR5969/Makefile
- demos/MSP430X/NIL-EXP430FR5969/chconf.h
- demos/MSP430X/NIL-EXP430FR5969/halconf.h
- demos/MSP430X/NIL-EXP430FR5969/main.c
- demos/MSP430X/NIL-EXP430FR5969/mcuconf.h
- os/common/ports/MSP430X/chcore.c
- os/common/ports/MSP430X/chcore.h
- os/common/ports/MSP430X/chcore_timer.h
- os/common/ports/MSP430X/compilers/GCC/chtypes.h
- os/common/ports/MSP430X/compilers/GCC/mk/port.mk
- os/common/startup/MSP430X/compilers/GCC/ld/msp430fr5969.ld
- os/common/startup/MSP430X/compilers/GCC/mk/startup_msp430fr5xxx.mk
- os/common/startup/MSP430X/compilers/GCC/rules.mk
- os/hal/boards/EXP430FR5969/board.c
- os/hal/boards/EXP430FR5969/board.h
- os/hal/boards/EXP430FR5969/board.mk
- os/hal/ports/MSP430X/hal_lld.c
- os/hal/ports/MSP430X/hal_lld.h
- os/hal/ports/MSP430X/hal_pal_lld.c
- os/hal/ports/MSP430X/hal_pal_lld.h
- os/hal/ports/MSP430X/hal_serial_lld.c
- os/hal/ports/MSP430X/hal_serial_lld.h
- os/hal/ports/MSP430X/hal_st_lld.c
- os/hal/ports/MSP430X/hal_st_lld.h
- os/hal/ports/MSP430X/platform.mk
This port includes hal, pal, serial, and st drivers. It supports both large and small model code and data for MSP430X-class CPUs. It has only been tested on the EXP430FR5969 LaunchPad board.
I wouldn't be surprised if there were some things that needed to be fixed before merging - any feedback is welcomed.
> Initial MSP430X Port.

- os/common/ext/CMSIS/KINETIS/kl25z.h
- os/common/ext/CMSIS/KINETIS/kl26z.h
- os/common/ext/CMSIS/KINETIS/kl27zxx.h
- os/common/ext/CMSIS/KINETIS/kl27zxxx.h
- os/common/ext/CMSIS/KINETIS/kl2xz.h
- os/hal/boards/FREESCALE_FREEDOM_KL26Z/board.h
- os/hal/ports/KINETIS/LLD/hal_i2c_lld.c
- os/hal/ports/KINETIS/LLD/hal_i2c_lld.h
- testhal/KINETIS/FRDM-KL26Z/I2C/Makefile
- testhal/KINETIS/FRDM-KL26Z/I2C/chconf.h
- testhal/KINETIS/FRDM-KL26Z/I2C/halconf.h
- testhal/KINETIS/FRDM-KL26Z/I2C/main.c
- testhal/KINETIS/FRDM-KL26Z/I2C/mcuconf.h
- testhal/KINETIS/FRDM-KL26Z/I2C/readme.txt
Slight rewrite of the I2C driver.
- shuffled the if branches in ISR around a bit, added some checks (e.g. master/slave), and comments
- removed S&S_BUSY waits (I haven't seen them in other kinetis I2C drivers and the datasheet also doesn't mention that it's needed - but I may be wrong about this)
- implemented timeouts
- fixed the base frequency for clock speed (SYS->BUS) as reported by Fred on the forums
- added a workaround for repeated start for KL27Z MCUs (as reported [here](https://community.freescale.com/thread/377611), my own tests confirm this)
> [KINETIS] I2C update (timeouts, KL27Z)

- testhal/KINETIS/FRDM-KL26Z/I2C/Makefile
Out-of-sync bug; just the same update as all the other Makefiles (ASMXSRC and license).
> [KINETIS] Fix KL26Z/I2C/Makefile.

- os/hal/ports/NRF51/NRF51822/hal_pal_lld.h
- os/hal/ports/NRF51/NRF51822/hal_pwm_lld.c
- os/hal/ports/NRF51/NRF51822/hal_pwm_lld.h
- testhal/NRF51/NRF51822/PWM/main.c
- testhal/NRF51/NRF51822/PWM/mcuconf.h
allow use of GPIOTE/PPI to drive gpio pin (without callback)
changed value of PAL_NOLINE to ((ioline_t)-1)
> allow use of GPIOTE/PPI in PWM to drive gpio pin

- os/hal/boards/NRF51-DK/board.h
- os/hal/include/hal_qei.h
- os/hal/ports/NRF51/NRF51822/hal_qei_lld.c
- os/hal/ports/NRF51/NRF51822/hal_qei_lld.h
- os/hal/ports/NRF51/NRF51822/platform.mk
- os/hal/src/hal_qei.c
Quadrature decoder for NRF51.
* Not tested with led pin (I don't have the necessary hardware)
* should I define a type for overflow_cb? or use the qeicallback_t?
* behaviour of counter overflow is user controllable
* trying to introduce new driver methods qeiSetCount and qeiAdjust (should it be in qei implementation?)
* are callback correctly handled? (they are supposed to be called from interrupts, or threads)
Comments and feedback are welcomed.
> QEI driver for NRF51

- os/hal/ports/KINETIS/LLD/hal_usb_lld.h
The upstream USB driver adds and uses 'saved_state' member of USBDriver struct. Done for kinetis.
> [KINETIS] Add saved_state to USB driver.

- os/hal/ports/STM32/LLD/CRCv1/hal_crc_lld.c
These asserts will trigger when !(config != default_config), and IMHO just reverse is expeceted when CRC is not programmable.
> STM32 CRC : Fix asserts

- testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/usbcfg.c
- testhal/KINETIS/FRDM-KL25Z/USB_SERIAL/usbcfg.c
- testhal/KINETIS/FRDM-KL26Z/USB_SERIAL/usbcfg.c
- testhal/KINETIS/MCHCK/USB_SERIAL/usbcfg.c
- testhal/KINETIS/TEENSY3_x/USB_SERIAL/usbcfg.c
Fix KINETIS USB_SERIAL testhal compilation by renaming the function
sduDisconnectI() to sduSuspendHookI().
> Fix KINETIS USB_SERIAL testhal compilation.

- os/hal/src/hal_usb_hid.c
Fix the compilation of hal_usb_hid.c that broke because of the changes
in ibqObjectInit() and obqObjectInit() prototypes.
In hidObjectInit() call these functions with the additional suspend
parameter set to true as done in ChibiOS-RT.
> hal: fix the compilation of hal_usb_hid.c

- testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/usbcfg.c
- testhal/KINETIS/FRDM-KL25Z/USB_HID/usbcfg.c
- testhal/KINETIS/FRDM-KL25Z/USB_SERIAL/usbcfg.c
- testhal/KINETIS/FRDM-KL26Z/USB_SERIAL/usbcfg.c
- testhal/KINETIS/MCHCK/USB_SERIAL/usbcfg.c
- testhal/KINETIS/TEENSY3_x/USB_SERIAL/usbcfg.c
Additional fixes for the testhal demos of the KINETIS boards:
* call sduWakeupHookI() when the device gets the USB_EVENT_WAKEUP event.
* handle USB_EVENT_RESET and USB_EVENT_UNCONFIGURED like it was USB_EVENT_SUSPEND.
The first patch was lightly tested on a teensy3.2 in linux by simulating a suspend event (echo auto > control in sysfs) and it worked as expected.
> Kinetis fixes

- os/hal/include/hal_usb_hid.h
Added some missing item defines, reformat macros.
> usb_hid: cosmetic improvements in report descriptor defines.

- os/hal/ports/STM32/LLD/DMA2Dv1/hal_stm32_dma2d.c
- os/hal/ports/STM32/LLD/LTDCv1/hal_stm32_ltdc.c
- testhal/STM32/STM32F0xx/qei/Makefile
- testhal/STM32/STM32F7xx/USB_MSD/Makefile
This PR fix the issue #111 about ChibiOS-RT dependency.
I have build successfully all the projects in `testhal/STM32` and `demos/STM32` so it should be sufficient.
While building the projects, I have encountered 2 minor issues that I have also fixed in this same PR.
> Fix ch dependency

- os/hal/ports/STM32/LLD/TIMv1/hal_qei_lld.h
For example PWM driver has the same checks: https://github.com/ChibiOS/ChibiOS/blob/master/os/hal/ports/STM32/LLD/TIMv1/hal_pwm_lld.h#L251-L306.
> Add checks to STM32 QEI driver if TIMx is already used

- os/hal/include/hal_usb_msd.h
- os/hal/src/hal_usb_msd.c
- os/various/lib_scsi.c
- os/various/lib_scsi.h
The SCSI library does not reply to certain inquiries made by a Windows host.
At least the Vital Product Data Page 80h, Unit Serial Number is required. If this is not handled correctly, the inquiry fails, and causes 3 retries with each having 20 second timeout/delay on mounting the drive.
This change will add this response. It also adds possibility to use your own response for it, but unfortunately it adds a argument to msdStart() function, which might not be ok. Therefore i pushed this here to rise conversation how this could be done more efficiently.
Maybe just always use a hardcoded default? This would not change msd api.
Sample capture of inquiry:
```
Inquiry
Requests the device server to return information regarding the logical unit and SCSI target device.
CBW
Offset Field Size Value …
```
> SCSI: Respond to unit serial number inquiry

- os/various/lib_scsi.c
When host sends TEST UNIT READY command, set sense 'all ok' if block device reports
that medium is inserted, or set sense 'medium not present' if medium is not inserted.
Do not override sense by default with 'all ok', allow REQUEST SENSE command
to be responded with correct sense data which was set on last failure.
Check just DESC bit when responding to REQUEST SENSE command.
----
Example use cases:
* Allow host to know the external media inserted state on your device
* Forcibly remount mass media by setting is_inserted virtual method return value to false for one round
Windows (at least) tells to "Insert disk in drive" when 
Analyzer capture (of latter use case)
```
Type	Seq	Time	Elapsed	Duration	Request	Request Details	I/O	C:I:E	Device Object	Device Name	Driver Name	IRP	IRP Status (URB …
```
> SCSI: Respond to TEST UNIT READY command, Fix REQUEST SENSE replying

- os/hal/ports/KINETIS/K20x/hal_lld.c
While working on QMK support for the K-Type keyboard (which uses this code) I ran into an issue where it would only start up about a third of the time. It was hanging on this:
```
/* Wait for the MCGOUTCLK to use the oscillator */¬
while ((MCG->S & MCG_S_CLKST_MASK) != MCG_S_CLKST(2));¬
```
I stumbled on this solution by accident but it seems to fix the issue by setting the C2 register using only one assignment, similar to how they do it in the reference manual.
https://github.com/qmk/qmk_firmware/pull/1963
> Fix for K20x startup

- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc.h
- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc_sdram.c
- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc_sdram.h
Tested on STM32F769I-Discovery DISC1 board.
> Add STM32F769 to FSMCv1 sdram driver

- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc.c
- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc.h
- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc_sdram.c
- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc_sdram.h
- os/hal/ports/STM32/LLD/FSMCv1/hal_fsmc_sram.c
Tested only for STM32F746, other chipsets have to be checked.
> Added support for STM32F7

- os/hal/ports/KINETIS/LLD/hal_usb_lld.h
This make it compatible with the 17.6.3 version, and maybe some earlier ones as well.
> Add usb_lld_wakeup_host for Kinetis

- os/common/ext/CMSIS/KINETIS/k20xx.h
- os/hal/ports/KINETIS/LLD/hal_usb_lld.c
This is another fix for the problem described in this thread http://www.chibios.com/forum/viewtopic.php?f=26&t=2401&sid=4e6ff9b730db4a2a8fe9254f9bc72680&start=40, the last post on the linked page. For me it was stil occuring with the exact symptoms when I tried to use the Virtual Serial port support. At least on Windows 10, it failed maybe once every 5 tries.
From the commit message 
> USB control transfers are structured as the following.
For incoming transfers
Setup (Data0 out)
Data (Data1/Data0 in) - starting with data 1
Status (Data1 out)
>For outgoing transfers
Setup (Data0 out)
Data (Data1/Data0 out) - starting with data 1
Status (Data1 in)
>The in buffers (device to host) are always correctly synchronized, since
they can always be reset to Data1 each setup packet without any …
> Fix Kinetis usb databank synchronization problems

- os/hal/ports/KINETIS/LLD/hal_sdc_lld.c
- os/hal/ports/KINETIS/LLD/hal_sdc_lld.h
This adds a low-level driver for the SDC driver which works with the SDHC peripheral found on several Kinetis chips. This was tested on a K64F on a Teensy 3.5.
> Add support for the Kinetis SDHC peripheral

- os/hal/ports/STM32/LLD/TIMv1/hal_eicu_lld.c
- os/hal/ports/STM32/LLD/TIMv1/hal_qei_lld.c
- os/hal/ports/STM32/LLD/TIMv1/hal_timcap_lld.c
RCC API changed in 01/2018 so apply the changes.
Note that ae7a4d40b84d8afc999691577210696f16e682f6 partially fixed the changes in QEI module but some were missing.
So update the other modules too.
> Keep track of STM32 RCC API

- os/hal/ports/STM32/STM32L4xx/platform.mk
This file allows to build for STM32L4xx platform.
I have only tested the QEI module.
So, do I have to only add this module or all of them and drop some if a user report an error?
> platform: add support for STM32L4 family

- os/hal/ports/KINETIS/MK66F18/kinetis_registry.h
This fixes a minor error causing SDHC not to work on the MK66F18 MCU.  After this fix, the SDHC driver wiml contributed is working on this MCU.  Tested using fatfs library.
> Adding missing interrupt vector for SDHC on MK66F18 MCU

- os/hal/ports/STM32/LLD/CRCv1/hal_crc_lld.c
- os/hal/ports/STM32/LLD/CRCv1/hal_crc_lld.h
Hi guys,
sorry for my issue duplicate.
As you already mentions correctly in #161 we have to split up the DMA transfer because the STM32 DMA can only handle 65535 bytes per transfer.
This is my current fix and the results are very promising.
What do you think about my solution?
> Fix #161: STM32 LLD CRCv1 large data bug in DMA mode

- os/hal/ports/STM32/LLD/CRCv1/hal_crc_lld.c
This was removed in commit
ae7a4d40b84d8afc999691577210696f16e682f6#diff-7ddaa5ecc31109f41b7801dea2660b47
But I think is still necessary as the underlying rccEnableAHB macros
take parameter 'lp'.  It seems to work for the F0xx series, because its
rccEnableAHB ignores the 'lp'.  It is required when I tried to use the
CRC driver on a family that does require the 'lp' parameter in the lower
level macros.
> Fix for rccEnableCRC macro parameter.

- os/hal/include/hal_qei.h
- os/hal/ports/STM32/LLD/TIMv1/hal_qei_lld.h
The qeiSetCount prototype was not in header file (causing -Wimplicit-function-declaration warning in gcc) plus the stm32 port had empty body of qei_lld_set_count.
> Added setting qei to value for stm32

- tools/mx2board.py
Some pins are ignored when the pin name in stm32cubemx xml is in format like:
PC14-OSC32_IN
PH0 - OSC_IN
This can cause build errors (e.g. for stm32f412 the VAL_GPIO_X are not defined in generated output and the build fails when the board.c tries to use these defines).
This patch fixes the port name generation.
> Fixed board generation for pins with note in name

- tools/mx2board.py
Added code for generation of peripheral and channel numbers. Eg. for ADC generate adc number and adc channel for each signal so it could be used in code. Similar to already existing generators for timers.
> Generate peripheral and channel numbers from signal names

- tools/mx2board.py
Hi, the mx2board script was not setting the the pins state for outputs correctly, by default the stm32cube sets pins to low, the default state in the script is high. Also the PinState value was not considered when generating the output.
> Added ODR setting to mx2board.py

- tools/mx2board.py
The latest stm32cube project file is crashing the mx2board.py - output low pin state is named GPIO_PIN_RESET instead of GPIO_PIN_CLEAR.
> Fixed GPIO_PIN_RESET instead of GPIO_PIN_CLEAR

- os/hal/ports/STM32/LLD/USBHv1/hal_usbh_lld.c
- os/hal/src/usbh/hal_usbh_msd.c
- os/various/fatfs_bindings/fatfs_diskio.c
- Fix return value on succesfull scsi_requestsense.
- Fix calls to LL SMT32 API for OTG2.
- Port changes from ChibiOS fatfs_diskio.
- Rework checks to allow simultaneous use of SD Card and USB MSD.
Signed-off-by: José Simões <jose.simoes@eclo.solutions>
> Fixes for USB MSD

- os/various/fatfs_bindings/fatfs_diskio.c
- This is required for F7 targets (and others that feature memory cache).
- The call is provided empty for all the other series, so it's OK to use it as it is.
> Add call to cache flush on disk write

- tools/mx2board.py
The I2C bus was not set to opendrain output type which caused very hard to find bugs.
> I2C not set as opendrain

- os/hal/ports/NRF5/LLD/TWIMv1/hal_i2c_lld.c
- os/hal/ports/NRF5/LLD/TWIMv1/hal_i2c_lld.h
- os/hal/ports/NRF5/LLD/TWIv1/hal_i2c_lld.c
- os/hal/ports/NRF5/LLD/TWIv1/hal_i2c_lld.h
Hello, I'm developing on a NRF52832-based board (DecaWave DWM1001) that has no external pull-up resistors on the I2C lines.
This patch adds two boolean I2C configuration options to optionally enable the MCU's internal pull-ups.
I've tested the patch on NRF52 only (TWIMv1) and it works for me. The NRF51 driver (TWIv1) looked very similar and I mirrored the changes there too, but I don't have a board to test it.
> NRF51/NRF52: Added support for internal I2C pull-ups

- os/hal/ports/NRF5/LLD/SPIv1/hal_spi_lld.c
Hello, the attached patch makes it possible to actually compile the SPI driver for NRF52832.
The driver was probably only developed for NRF51, where the IRQ is simply called `SPI0_TWI0_IRQn`. On NRF52, the same IRQ is called `SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQn`, therefore the current code doesn't compile, complaining that `SPI0_TWI0_IRQn` is not defined.
The attached patch defines `SPI0_TWI0_IRQn` as an alias for `SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQn` if we are compiling for NRF52. This is the same approach already adopted for the UART driver.
I have tested the resulting driver on a real board, and it works flawlessly.
> NRF: Make the SPI driver compile on NRF52 too

- demos/STM32/RT-STM32F303-DISCOVERY-PID/main.c
https://github.com/ChibiOS/ChibiOS/commit/f20ecc78178fc8cdfa682e100398c240224dbb4a#diff-e42edbbb9a343d9d1b70e68f524cbc22
I see that there is a Jenkinsfile that should catch this kind of API breakage but here it was only a warning:
> Compiling main.c                                                                                                                                                                   
main.c:64:3: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
adccallback,
^~~~~~~~~~~
main.c:64:3: note: (near initialization for 'adcgrpcfg1.end_cb')
Is the Jenkins running those tests publicly available?
> FIX PID demo after ChibiOS ADC callback rework
