os/various/devices_lib/l3gd20.c
os/various/devices_lib/l3gd20.h
os/various/devices_lib/lis3mdl.c
os/various/devices_lib/lis3mdl.h
os/various/devices_lib/lsm303dlhc.c
os/various/devices_lib/lsm303dlhc.h
os/various/devices_lib/lsm6ds0.c
os/various/devices_lib/lsm6ds0.h
os/various/devices_lib/max7219.c
os/various/devices_lib/max7219.h
os/various/devices_lib/nrf24l01.c
os/various/devices_lib/nrf24l01.h

Devices lib added:
L3GD20, LIS3MDL, LSM6DS0, LSM303DLHC, MAX7219, NRF24L01

Added devices_lib

---

os/various/devices_lib/l3gd20.c
os/various/devices_lib/l3gd20.h
os/various/devices_lib/lis3mdl.c
os/various/devices_lib/lis3mdl.h
os/various/devices_lib/lsm303dlhc.c
os/various/devices_lib/lsm303dlhc.h
os/various/devices_lib/lsm6ds0.c
os/various/devices_lib/lsm6ds0.h
os/various/devices_lib/max7219.c
os/various/devices_lib/max7219.h
os/various/devices_lib/nrf24l01.c
os/various/devices_lib/nrf24l01.h

Added email contact, Fixed Bug on chDbgAssert() passing 2 arguments instead of 3

Modified files under os/various

---

os/hal/ports/NRF51/NRF51822/nrf51.h
os/hal/ports/NRF51/NRF51822/nrf51_bitfields.h
os/hal/ports/NRF51/NRF51822/pal_lld.c
os/hal/ports/NRF51/NRF51822/pal_lld.h

Pending approval by utzig.
Can't find an easy way to make dependent pull requests, so I'll hold off submitting the serial cleanup pull request until this one is merged (since the serial one depends on this one).

nRF51 Cleanup PAL

---

os/hal/boards/NRF51-DK/board.c
os/hal/boards/NRF51-DK/board.h
os/hal/boards/NRF51-DK/board.mk

NRF51 DK board

---

os/hal/ports/NRF51/NRF51822/serial_lld.c
os/hal/ports/NRF51/NRF51822/serial_lld.h

Adding support for hardware flow control

hardware flow control from nRF51

---

os/hal/ports/NRF51/NRF51822/platform.mk

Only compile *_lld.c file according to halconf.h

Smart build enable

---

os/hal/boards/NRF51-DK/board.c

Ensure RAM bank is powered.
I guess the same should also be applied to WVSHARE?

Ensure ram is on

---

os/hal/hal.mk
os/hal/include/ee24xx.h
os/hal/include/ee25xx.h
os/hal/include/eeprom.h
os/hal/include/hal_community.h
os/hal/src/ee24xx.c
os/hal/src/ee25xx.c
os/hal/src/eeprom.c
testhal/STM32/STM32F3xx/EEProm/Makefile
testhal/STM32/STM32F3xx/EEProm/chconf.h
testhal/STM32/STM32F3xx/EEProm/halconf.h
testhal/STM32/STM32F3xx/EEProm/halconf_community.h
testhal/STM32/STM32F3xx/EEProm/main.c
testhal/STM32/STM32F3xx/EEProm/mcuconf.h
testhal/STM32/STM32F3xx/EEProm/mcuconf_community.h

This comes after the USB Host driver.
The original driver was from barthess, modified by timonwong, I fixed/cleaned it for 3.x/16.x+
Url: https://github.com/timonwong/ChibiOS-EEPROM
Testhal included, tested on real hardware as well for the SPI part.

EEPROM Driver

---

testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/Makefile
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/chconf.h
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/chtsy.inf
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/halconf.h
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/main.c
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/mcuconf.h
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/usbcfg.c
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/usbcfg.h

Here is the addition of the FRDM-K20D50M USB_SERIAL project.
I changed the stream and shell to use the makefiles that are now part of the main ChibiOS. Let me know if that is not desired and I should change them back.

[KINETIS] Added USB_SERIAL testhal for FRDM-K20D50M board

---

demos/KINETIS/RT-FREEDOM-K20D50M/main.c
demos/KINETIS/RT-FREEDOM-KL25Z/main.c
demos/KINETIS/RT-TEENSY3/main.c
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/main.c
testhal/KINETIS/FRDM-KL25Z/USB_SERIAL/chconf.h
testhal/KINETIS/FRDM-KL25Z/USB_SERIAL/main.c
testhal/KINETIS/FRDM-KL26Z/USB_SERIAL/chconf.h
testhal/KINETIS/FRDM-KL26Z/USB_SERIAL/main.c
testhal/KINETIS/MCHCK/USB_SERIAL/main.c
testhal/KINETIS/TEENSY3_x/USB_SERIAL/main.c

This fixes build of all demos and testhal that uses the test thread.

Fix kinetis test thd

---

os/hal/boards/WVSHARE_BLE400/board.h

Added #define for CTS / RTS pin

define CTS/RTS for BLE400 board

---

demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/Makefile
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/chconf.h
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/halconf.h
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/main.c
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/mcuconf.h
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/shellcfg.c
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/shellcfg.h
demos/KINETIS/RT-FREEDOM-KL25Z-SHELL/shellconf.h
testhal/KINETIS/FRDM-K20D50M/USB_SERIAL/main.c
testhal/KINETIS/FRDM-KL25Z/USB_SERIAL/main.c

I added the shell demo project that I've been using to test the shell enhancements that I've been working on and that Giovanni recently committed to ChibiOS trunk. It has an example shellconf.h file that can be used to enable the extra features.

Added shell demo project

---

demos/NRF51/OSHCHIP_V1.0/Makefile
demos/NRF51/OSHCHIP_V1.0/chconf.h
demos/NRF51/OSHCHIP_V1.0/debug/openocd.cfg
demos/NRF51/OSHCHIP_V1.0/halconf.h
demos/NRF51/OSHCHIP_V1.0/main.c
demos/NRF51/OSHCHIP_V1.0/mcuconf.h
demos/NRF51/OSHCHIP_V1.0/patch_hex.sh
demos/NRF51/OSHCHIP_V1.0/readme.txt
os/hal/boards/OSHCHIP_V1.0/board.c
os/hal/boards/OSHCHIP_V1.0/board.h
os/hal/boards/OSHCHIP_V1.0/board.mk

Adds board files and a demo for [OSHchip](http://oshchip.org/).

Add OSHchip board (NRF51 based)

---

os/hal/ports/KINETIS/LLD/hal_adc_lld.c

Applies bunnie's fix: http://forum.chibios.org/phpbb/download/file.php?id=1008

[KINETIS] fix ADC LLD bug, grpp access after clear

---

os/hal/ports/NRF51/NRF51822/hal_pwm_lld.c
os/hal/ports/NRF51/NRF51822/hal_pwm_lld.h
os/hal/ports/NRF51/NRF51822/platform.mk
testhal/NRF51/NRF51822/PWM/Makefile
testhal/NRF51/NRF51822/PWM/chconf.h
testhal/NRF51/NRF51822/PWM/halconf.h
testhal/NRF51/NRF51822/PWM/main.c
testhal/NRF51/NRF51822/PWM/mcuconf.h

callback only supported for now (no GPIOTE/PPI shortcuts)

PWM support for nRF51

---

os/hal/boards/PJRC_TEENSY_LC/board.c
os/hal/ports/KINETIS/LLD/hal_i2c_lld.h
os/hal/ports/KINETIS/LLD/hal_pal_lld.c
os/hal/ports/KINETIS/LLD/hal_usb_lld.c

Caught a few leftovers when trying to go osal+HAL.

[KINETIS] Fixes for kernel-less builds.

---

os/hal/ports/NRF51/NRF51822/hal_gpt_lld.h
os/hal/ports/NRF51/NRF51822/hal_i2c_lld.h
os/hal/ports/NRF51/NRF51822/hal_pwm_lld.h
os/hal/ports/NRF51/NRF51822/hal_rng_lld.h
os/hal/ports/NRF51/NRF51822/hal_serial_lld.h
os/hal/ports/NRF51/NRF51822/hal_spi_lld.h
os/hal/ports/NRF51/NRF51822/hal_st_lld.h

Enable priority validation, Fixed priorirty (nRF51 use a 2bit priority)

---

os/hal/boards/NRF51-DK/board.h
os/hal/boards/WVSHARE_BLE400/board.h

Added pins definitions for AIN/AREF

Added Analog input/ref pins

---

os/hal/hal.mk
os/hal/include/hal_community.h
os/hal/include/hal_usb_hid.h
os/hal/src/hal_usb_hid.c
testhal/KINETIS/FRDM-KL25Z/USB_HID/Client/Makefile
testhal/KINETIS/FRDM-KL25Z/USB_HID/Client/test-usb-hid.c
testhal/KINETIS/FRDM-KL25Z/USB_HID/Client/udev.rules
testhal/KINETIS/FRDM-KL25Z/USB_HID/Makefile
testhal/KINETIS/FRDM-KL25Z/USB_HID/chconf.h
testhal/KINETIS/FRDM-KL25Z/USB_HID/halconf.h
testhal/KINETIS/FRDM-KL25Z/USB_HID/halconf_community.h
testhal/KINETIS/FRDM-KL25Z/USB_HID/main.c
testhal/KINETIS/FRDM-KL25Z/USB_HID/mcuconf.h
testhal/KINETIS/FRDM-KL25Z/USB_HID/usbcfg.c
testhal/KINETIS/FRDM-KL25Z/USB_HID/usbcfg.h

I added an HID driver based off of the USB Serial driver. Please let me know if I should change anything.

Added USB HID driver to community HAL

---

os/hal/include/hal_qei.h
os/hal/ports/NRF51/NRF51822/hal_qei_lld.c
os/hal/ports/STM32/LLD/TIMv1/hal_qei_lld.c
os/hal/ports/STM32/LLD/TIMv1/hal_qei_lld.h
os/hal/src/hal_qei.c
testhal/STM32/STM32F0xx/qei/Makefile
testhal/STM32/STM32F0xx/qei/halconf_community.h

Created qeiAdjustI.
Modified STM32 to add new field and sanity check.
I forgot to commit it, in the previous pull request
I'll let you see if it is a good idea to merge it now or not.

qeiAdjustI

---

os/hal/ports/NRF5/NRF51822/hal_pal_lld.c
os/hal/ports/NRF5/NRF51822/hal_pal_lld.h

use IOPORT1 instead of NRF_GPIO

---

os/hal/src/hal_onewire.c

Tested with DS18S20 temperature sensor on STM32F072, working fine.

set sampling channel PWM output to disabled so the IO pin is free

---

os/hal/src/hal_onewire.c

Hello,
Just some typo fixes here.
Thanks

1-Wire. Just typo fix

---

os/hal/ports/NRF5/NRF51822/hal_pwm_lld.c
os/hal/ports/NRF5/NRF51822/hal_pwm_lld.h

Used the same technique as the nrf51-pwm-library in Nordic github

Use active wait and perform extra toggle if needed.

---

tools/chibios.el

* Use 2 space indentation
* No tab

C styling for emacs editor

---

os/hal/hal.mk
os/hal/include/hal_community.h
os/hal/include/hal_comp.h
os/hal/ports/STM32/LLD/COMPv1/hal_comp_lld.c
os/hal/ports/STM32/LLD/COMPv1/hal_comp_lld.h
os/hal/ports/STM32/STM32F3xx/platform.mk
os/hal/src/hal_community.c
os/hal/src/hal_comp.c
testhal/STM32/STM32F3xx/COMP/Makefile
testhal/STM32/STM32F3xx/COMP/chconf.h
testhal/STM32/STM32F3xx/COMP/halconf.h
testhal/STM32/STM32F3xx/COMP/halconf_community.h
testhal/STM32/STM32F3xx/COMP/main.c
testhal/STM32/STM32F3xx/COMP/mcuconf.h
testhal/STM32/STM32F3xx/COMP/mcuconf_community.h

This is a driver for the Comparator peripherals.
I need to do some testing but you can already look at the code.

Comparator Driver

---

os/hal/include/usbh/dev/uvc.h
os/hal/ports/STM32/LLD/USBHv1/hal_usbh_lld.c
os/hal/src/usbh/hal_usbh_msd.c
os/hal/src/usbh/hal_usbh_uvc.c

- Fix compile with IAR (tested with IAR EWARM 7.50 on custom board with STM32F411@100MHz)
- Fix mass storage driver EP reset bug

USBH: fix compile with IAR

---

os/hal/include/hal_usbh.h
os/hal/include/usbh/dev/aoa.h
os/hal/include/usbh/dev/ftdi.h
os/hal/include/usbh/dev/hid.h
os/hal/include/usbh/dev/hub.h
os/hal/include/usbh/dev/msd.h
os/hal/include/usbh/dev/uvc.h
os/hal/include/usbh/internal.h
os/hal/include/usbh/list.h
os/hal/ports/STM32/LLD/USBHv1/hal_usbh_lld.c
os/hal/ports/STM32/LLD/USBHv1/hal_usbh_lld.h
os/hal/src/hal_usbh.c
os/hal/src/usbh/TODO.txt
os/hal/src/usbh/hal_usbh_aoa.c
os/hal/src/usbh/hal_usbh_debug.c
os/hal/src/usbh/hal_usbh_ftdi.c
os/hal/src/usbh/hal_usbh_hid.c
os/hal/src/usbh/hal_usbh_hub.c
os/hal/src/usbh/hal_usbh_msd.c
os/hal/src/usbh/hal_usbh_uvc.c
testhal/STM32/STM32F4xx/USB_HOST/Makefile
testhal/STM32/STM32F4xx/USB_HOST/halconf_community.h
testhal/STM32/STM32F4xx/USB_HOST/main.c
testhal/STM32/STM32F4xx/USB_HOST/usbh_additional_class_drivers.h
testhal/STM32/STM32F4xx/USB_HOST/usbh_custom_class_example.c
testhal/STM32/STM32F4xx/USB_HOST/usbh_custom_class_example.h

Hi, these are some bug corrections and some improvements.
Some of them are:
- Added mechanism for out-of-tree class drivers. This will be probably improved further in the future.
- Added a workaround for an undocumented erratum in the STM32 OTG core (appears only with low speed devices).
- Improved robustness for STM32 OTG driver.
- HID: synchronization, minor bug correction.
- MSD: synchronization
- Various cleanups
Thanks,
Diego.

USBH: Various improvements

---

os/hal/ports/TIVA/LLD/SSI/hal_spi_lld.c
os/hal/ports/TIVA/LLD/SSI/hal_spi_lld.h

Updated the SPI driver to the latest changes regarding the spiSelect/spiUnselect API.

Aligned the Tiva port to the SPI driver improvements.

---

os/hal/ports/KINETIS/LLD/hal_serial_lld.c
os/hal/ports/KINETIS/LLD/hal_serial_lld.h

Also moved some code that is duplicated per-UART into local functions to reduce the amount of duplication.
I've tested this on a MK64FX512 and a MK20DX256VLH7, but I don't have a K20x5 or a KL2x to test on those chips.

Added support for additional UARTs (up to six on the K64F).

---

tools/mx2board.py

Added generation of PAL_LINE defines from stm32cubemx config file.

Generate PAL_LINE for named pins

---

os/hal/ports/STM32/LLD/USBHv1/hal_usbh_lld.c

As per commit messages:
- implement support for ISO/INT out transfers
- some minor compiler warning fixes related to debug log levels
- fix a potential infinite loop when closing an endpoint

STM32 USBH LLD Fixes

---

os/hal/include/hal_opamp.h
os/hal/ports/STM32/LLD/OPAMPv1/hal_opamp_lld.c
os/hal/ports/STM32/LLD/OPAMPv1/hal_opamp_lld.h
os/hal/src/hal_opamp.c
testhal/STM32/STM32F3xx/OPAMP/main.c
testhal/STM32/STM32F3xx/OPAMP/mcuconf_community.h

I've cleaned the opamp driver to make it more consistent.

Updating OpAmp code with calibration functions, cleaning.

---

os/various/fatfs_bindings/fatfs_diskio.c

- This should be the correct fix.

Fix F7 cache invalidation on write operation

---

demos/STM32/RT-STM32F411-DISCOVERY-blinker/Makefile
demos/STM32/RT-STM32F411-DISCOVERY-blinker/cfg/chconf.h
demos/STM32/RT-STM32F411-DISCOVERY-blinker/cfg/halconf.h
demos/STM32/RT-STM32F411-DISCOVERY-blinker/cfg/mcuconf.h
demos/STM32/RT-STM32F411-DISCOVERY-blinker/main.c
demos/STM32/RT-STM32F411-DISCOVERY-blinker/usbcfg.c
demos/STM32/RT-STM32F411-DISCOVERY-blinker/usbcfg.h
os/hal/boards/ST_STM32F411_DISCOVERY/board.c
os/hal/boards/ST_STM32F411_DISCOVERY/board.h
os/hal/boards/ST_STM32F411_DISCOVERY/board.mk

Not sure whether this is perfect or not, but it worked well for me.

+ Added board files and example for STM32F411-Discovery board

---

os/hal/ports/NRF5/LLD/ADCv2/driver.mk
os/hal/ports/NRF5/LLD/ADCv2/hal_adc_lld.c
os/hal/ports/NRF5/LLD/ADCv2/hal_adc_lld.h
os/hal/ports/NRF5/LLD/TIMERv1/hal_st_lld.h
os/hal/ports/NRF5/NRF52832/platform.mk
testhal/NRF52/NRF52832/ADC/Makefile
testhal/NRF52/NRF52832/ADC/chconf.h
testhal/NRF52/NRF52832/ADC/halconf.h
testhal/NRF52/NRF52832/ADC/halconf_community.h
testhal/NRF52/NRF52832/ADC/main.c
testhal/NRF52/NRF52832/ADC/mcuconf.h

Checked with provided sample (on other custom board though).

Driver for new ADC peripheral (called SAADC) in NRF52 devices.
